version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crud-db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
